### ISSUE TITLE
Document long-term roadmap

### ISSUE THREAD

**Issue by bast** [openrsp/openrsp#18]
Taken from the decommissioned `TODO.rst` file, not sure if still relevant or up-to-date:

- Changes to perturbation free scheme
- Implements the symbolic operations
- Adds response theory based on molecular orbital coefficients? coupled cluster?

**Comment by bingao** [comment]
Hi @bast 

These 3 are still in my plan, but they are not for this release. According to your opinion, where is good place to put long-term projects on Github?

**Comment by bast** [comment]
I would put it either under `doc/` or into the `README.rst`. I agree that it's not top prio.

**Comment by bingao** [comment]
OK. I will move them into `doc` and close this issue once it is done.
