### ISSUE TITLE
Second round polish of website/documentation

### ISSUE THREAD

**Issue by ringholm** [openrsp/openrsp#29]
Some parts of the documentation on the website are out of date and should be updated before the release. Several of these parts are described in the review comments for pull request https://github.com/openrsp/openrsp/pull/27 which can be a starting point for working on this issue.

**Comment by bast** [comment]
The repo now correctly updates/renders to http://openrsp.org so the cleanup can start.

**Comment by bingao** [comment]
I think this issue and the unit testing issue are more important for this release.

I will first work on the unit testing, and back to this issue afterwards.

**Comment by ringholm** [comment]
I agree - as long as we remember to get back to it :)

**Comment by bingao** [comment]
Hi,

Just let you know, I started to work on this issue since yesterday. I am, more or less sure a first draft can be finished during the weekend.

**Comment by bast** [comment]
Cool! Can you please self-assign? This will signal to others that you are working on it.

**Comment by bast** [comment]
... to avoid double-work, dead-locks, and conflicts. At any moment you can again un-assign to signal that you are not working on it.

**Comment by bingao** [comment]
OK. But I do need others' review afterwards. Means that I prefer more people can have a look at the generated HTML files at http://www.openrsp.org, and correct if there is anything incorrect.

**Comment by bast** [comment]
Review is required anyway. And self-assigning does not mean that you will do everything, it just means that you work on it now and may hand it over to somebody else.

**Comment by bast** [comment]
Fixing the text on the website is a collective effort, just to avoid any doubt - this is not all on you to fix.

**Comment by ringholm** [comment]
How about @bingao does a first pass, then I can take the next pass and then assign more isolated tasks to the people who would best be able to deal with them?

**Comment by bingao** [comment]
> How about @bingao does a first pass, then I can take the next pass and then assign more isolated tasks to the people who would best be able to deal with them?

Agreed.

**Comment by bingao** [comment]
Hi,

I almost finish the first draft, probably I can make a pull request tonight. Two questions:

To @ringholm could you please check if http://www.openrsp.org/en/latest/modularization.html is still needed. Because the specification of perturbations have been described in http://www.openrsp.org/en/latest/manual/openrsp_introduction.html#openrsp-notations-and-conventions and http://www.openrsp.org/en/latest/manual/openrsp_api.html

To @bast will the website http://www.openrsp.org automatically updated after PR?

Thank you.

**Comment by ringholm** [comment]
@bingao  http://www.openrsp.org/en/latest/modularization.html should be safe to remove.

**Comment by bast** [comment]
Yes, website should auto-update after merge.

**Comment by bast** [comment]
I think this issue is too diffuse - it may not be clear when this is "solved". I think we should split it up into smaller, more concrete tasks.

**Comment by bingao** [comment]
> How about @bingao does a first pass, then I can take the next pass and then assign more isolated tasks to the people who would best be able to deal with them?

Hi @bast 

Thank you. I guess @ringholm will split it up once he finishes his pass, according to our previous discussion.

**Comment by bingao** [comment]
Hi @bast 

May I ask what the appropriate/efficient way is, if I want to do minor corrections to the documentation (such as typos) and merge into the master? Thank you.

**Comment by bingao** [comment]
Can we make a branch in this repository, only for documentation work? So that everyone can work on this branch, and once done, we merge it into master?

**Comment by ringholm** [comment]
Yes, we can do that. @bingao Do I understand the log correctly that your work is now merged into master? If so, I will make a new branch to do my pass and we can continue working from there.

**Comment by bingao** [comment]
Hi!

Sorry that I am working on some typo fixing. Please wait for a few hours (or less). I will make a pull request once I finish.

Then you can start :-)

**Comment by ringholm** [comment]
OK, sounds good! I saw the pull request on https://github.com/openrsp/openrsp/pull/32/ when I came back to work now and I thought that was your last piece of work for this iteration.

**Comment by bingao** [comment]
Yes, I thought too. But I found some typos and minor issues that it is better I fix before hand over to you guys :-)

**Comment by bingao** [comment]
Hei @ringholm 

I finished my first round for the work of website and documentation. I have changed the name of this issue and unassigned myself so that you can now start your round.

I am going to create a few issues regarding the documentation and website (probably most of them are trivial changes on the documentation), and assign some of them to individual persons who I think are the appropriate guys :-)

As such, to @bast and @ringholm could you please decide which strategy will be good for us working on such (trivial) changes and merge? Thank you.

**Comment by ringholm** [comment]
Thank you @bingao for this work! I will start looking at it now and continue tomorrow. I will first read the issues you started and see what I can do about those, then do a more general pass on the documents.

**Comment by bingao** [comment]
Hi @ringholm 

I saw you created a branch `documentation-second-pass`, which I understand you will have your work on this branch, right?

If yes, I hope you would not mind that I just push a typo fix to this branch :-)

**Comment by ringholm** [comment]
@bingao you are correct that this is the branch I use and feel free to push to it :)

**Comment by ringholm** [comment]
@bingao @bast @KennethRuud I have been browsing the website as it is now and I am starting to think that we should do a substantial reorganization over the present form.

What I suggest as a starting point for discussion is the following general structure:

* Brief introduction: 
  * What is OpenRSP and what can it do?
  * Why is it good to use?
  * Brief history
* Authors
* Programs where OpenRSP is implemented: We add LSDalton here once it is released with OpenRSP
* Papers where OpenRSP was used in calculations
* Changelog (should maybe instead be on GitHub)
* Known issues (should maybe instead be on GitHub)
* "Do you want to learn how OpenRSP works? Here's how:"
  * References to articles about the approach starting with Andreas Thorvaldsen's 2008 paper
  * Maybe also link to the API documentation and documentation about the core routines once completed
* "Do you want to use OpenRSP for calculations? Here's how:"
  * Link to the LSDalton repository once it is released
  * Link to the citation guide
* "Do you want to use OpenRSP in a host program? Here's how:"
  * Link to the API documentation
  * Link to the OpenRSP GitHub repository
* "Do you want to develop OpenRSP itself? Here's how:"
  * Link to the API documentation
  * Link to documentation about the core routines once completed
  * Link to style guide and Git workflow requirements once ready
  * Link to the OpenRSP GitHub repository

We may find that some of the files that are already there don't fit into this format and then I suggest to take them out. I think the current website a) makes it difficult for an outside visitor to find out what she wants, b) contains some outdated information, c) contains some information that is better viewed as a basis for internal reference or dialogue.

Any views on this?

**Comment by bingao** [comment]
Hi,

I think your proposed structure is better. But I doubt if we have enough time to make it ready for the desired date of release.

To summarise, I think we need to first consider how many days/weeks needed for such a reorganization and modification. If it will take too long, I would suggest that we reorganize it after the release.

**Comment by ringholm** [comment]
I think this is a interesting point about the time use and this is my view about it: 

1. The website is not currently in a good enough state to properly serve its purpose when we release the code.
2. The work needed to bring the website to that state will anyway be substantial. 
3. Reorganizing it in a format like the one I suggest may not take much more time than what we would anyway need to do for point 2 - and it might possibly even save time because it can be easier to prioritize and put a direction on the remaining work (and not do work in places that are not as important).

**Comment by bast** [comment]
I agree that this would be good. Especially we need to make very clear what OpenRSP is about and for in 2 sentences. Let's do one step at a time, let's keep issues and PRs small. Whatever we have no time to do now, let's spawn new issues.

**Comment by ringholm** [comment]
I also want to say that as long as the bare minimum is in place, I would rather that missing parts be added later than having live on the website documents that may cover them, but in a possibly unpolished form or a form that is tricky to navigate. What I consider the bare minimum may not include everything in the above list.

Maybe we could even begin by clearing out the entire website and fill in the list above (or something we agree on like it) from what we have. I think we can fill quite a lot in this way. Then we gradually add remaining pieces.

**Comment by bingao** [comment]
Let me just give an approximate time needed for my part:

#. Files in `doc/manual` and `doc/tutorial`, and
#. Files `doc/developer/background_and_rationale.rst` and `doc/developer/openrsp_design.rst`.

If it requires me to reorganize the above files to fit the proposed new structure, I need at least 2 weeks or more. It not only the problem of just putting these files into some place, but also rewriting some text in them, and removing some chapters, and merging some chapters, etc.

Moreover, I have used one full week time to finish the first round of documentation. I need to work on other projects (integrals, matrix, etc.) and other OpenRSP issues (for example, unit testing), which means there will be less time for me to work on the documentation issue, I am afraid.

**Comment by bast** [comment]
I think it's fine if we continue after release. Also I do not expect that people will storm our doors and proof-read our documentation on day 1.

**Comment by ringholm** [comment]
@bast I agree that we don't need all of this to be ready by the release, and @bingao I agree that spending two weeks on this now is a bit too much. However, I think I would prefer that documents that are not fully developed and organized yet are not put on the website until they are. I can take care of starting the reorganization and putting first only the most essential information there. Then we can expand on this when we are ready. How does that sound?

**Comment by bast** [comment]
I think reorganization is no problem but let's merge the open work ASAP, let's have short-lived branches, let's close then issues which are done and then we can iteratively improve.

**Comment by bingao** [comment]
Hei @ringholm

Thank you for taking care of this. I am OK if you believe it is manageable.

**Comment by ringholm** [comment]
OK, just to check if we all agree on this plan: 

* I will PR the latest website work into master, then start a new branch from that (let's call it `website_overhaul`. 
* In this branch, I will clear the website and reassemble it in the shape of the above list using the parts we have. 
* I will do the most essential stuff for now and leave out things that are less essential or entail too much rewriting - but we will do that work later. 
* I will branch out from `website_overhaul` for each sensible part of the work and PR back into `website_overhaul`. I will ask you @bingao and @bast to review these PRs as they come in.

**Comment by bingao** [comment]
Hi @ringholm 

Sounds good.

A question regarding the release: is there any deadline for the release now?

**Comment by ringholm** [comment]
The new deadline that was discussed is to my knowledge November 15 but publicly (see https://twitter.com/daltonprogram/status/1057639749668634628 ) it is just "further delayed".

**Comment by ringholm** [comment]
Closing this issue.
