### ISSUE TITLE
Affiliations of authors

### ISSUE THREAD

**Issue by bingao** [openrsp/openrsp#34]
To @danielhfriese 

I have changed your affiliation at doc/authors.rst, could you please check if it is OK.

To @ringholm will you change your affiliation?

**Comment by bingao** [comment]
Daniel is not in the openrsp organization yet. Could @bast please invite him?

**Comment by bast** [comment]
OK I will write an email to Daniel.

**Comment by bast** [comment]
@danielhfriese is invited.

**Comment by bingao** [comment]
Hi @bast 

@danielhfriese is Daniel's GitHub account, right?

**Comment by bast** [comment]
Right.

**Comment by ringholm** [comment]
I think I should leave the affiliation as it is since I am still formally employed by UiT.

**Comment by bingao** [comment]
OK. Then we can close this issue once the affiliation of Daniel is confirmed.
