### ISSUE TITLE
Sphinx and documentation

### ISSUE THREAD

**Issue by bingao** [openrsp/openrsp#35]
I find doc/manual/sphinx.rst should be updated. Would it be also better that we describe how to generate documentation (HTML, PDF etc.) from the rst files?

I also add a sentence in the `README.rst`:

> OpenRSP documentation can be built by following doc/manual/sphinx.rst

Please feel free to change it if you like.

**Comment by ringholm** [comment]
The sphinx.rst page does not currently appear on the new version of the website. Should we keep this issue or close it?

**Comment by bast** [comment]
I will look at this and either reactivate or ditch depending on its state.
