### ISSUE TITLE
Update/rewrite Daniel's code documentation

### ISSUE THREAD

**Issue by bingao** [openrsp/openrsp#38]
@danielhfriese has written a nice documentation regarding the core part of OpenRSP. I am not sure if it is updated and ready to put on the website and be public.

Therefore, could you guys please have a look at [Daniel’s code documentation](http://www.openrsp.org/en/latest/developer/pseudocode.html) or this file `doc/developer/pseudocode.rst` and make a decision?

**Comment by bast** [comment]
The code has changed a lot since last time I wrote inside OpenRSP and I haven't written this particular documentation so I am not in a position to judge whether it is up to date or not. If we are unsure, we can put a warning banner on top.

**Comment by ringholm** [comment]
If I remember correctly, this document was originally Daniel's own notes for learning the inner workings of OpenRSP and was since developed into the current document. However, from a brief look I don't think it is up-to-date with the most recent version of the code. Going through this and verifying with the code appears to me to be a several-day job.

**Comment by bingao** [comment]
Then I suggest we remove it from "Documentation for developers". I will do it.

**Comment by bast** [comment]
But what does remove really mean? Will the sources of it remain in the repo?

**Comment by bingao** [comment]
“Remove” is not the right word. I should say I remove the reference to it in documentation, but still keep the file in the repository.

It is for your guys to decide if also removing the file or not.

**Comment by ringholm** [comment]
I prefer for now a solution where we do not show it on the website but keep it in the repository. Later we decide on a plan for this document.

**Comment by bingao** [comment]
Hei Magnus,

I chose your solution, and pushed to the second pass branch, in which this file is not shown on the website.

**Comment by bast** [comment]
But with this we create dead code. Nobody will see it, nobody will see that it is outdated and getting more outdated by the day.

**Comment by ringholm** [comment]
It is not dead (and in a sense also not code) but we haven't decided just what to do with it yet. Do you think we should just remove it?

**Comment by bingao** [comment]
My understanding is we will work on this file later, not now because we do not have enough time and it is not important for the current release. Therefore it is not dead code.

My solution is we do not show this file on website, but mention we will work on it in an issue and/or in limitations and future plans. I can add such information to the second pass branch.

**Comment by bast** [comment]
If it is totally outdated and irrelevant, we should remove it.
If it is slightly outdated and can be made relevant, we can:
- remove it from the website and create an issue to reactivate
- leave it on the website with a big warning banner that this is possibly outdated

Removing from the website and not following up in an issue is not an option for me: this will create dead documentation sources.

**Comment by bingao** [comment]
I have removed this file from website, and add an item in future plans (`doc/manual/future_plans.rst`) like:

`* Update/rewrite :doc:`Daniel’s code documentation
  <../developer/pseudocode.rst>` for developers, based on the current
  implementation of the "OpenRSP response" part (see :ref:`openrsp_framework`)`

As I understand, @ringholm and @danielhfriese could be the appropriate persons to fix this documentation.

Therefore, I will change the name of this issue to "Update Daniel’s code documentation" and keep it open, and remove @bast and @KennethRuud from the assignees.

**Comment by bast** [comment]
Why not create an issue instead of listing it under future plans?

**Comment by ringholm** [comment]
I am making my way to the future plans document in my work on the website. My preliminary opinion is that we should consider removing that page and have such plans be described by milestones and issues in the repository.

**Comment by bast** [comment]
It's OK to have a roadmap documented somewhere but "future plans" should IMO not be a place to hide away issues that are better tracked as issues.

For me issues are issues that anybody can take up. Roadmap is something that we plan to do eventually.

If I visit a new project and want to know: "what issues do the developers know about?" - I check issues and not the roadmap/future plans.

**Comment by bingao** [comment]
Hi

Here are the plans:

1. Update/rewrite :doc:`Daniel’s code documentation <../developer/pseudocode.rst>` for developers, based on the current implementation of the "OpenRSP response" part (see :ref:`openrsp_framework`)
2. Change or abandon literate programming approach (because of extra work on maintenance and further development)
3. Add more unit tests (currently only polarizability)
4. Change API codes to C++
5. Add Fortran unit testing
6. Implement symbolic computations (see Symbolic Computations (not implemented))
7. Implement perturbation free scheme (see Perturbation Free Scheme (not implemented))
8. Add response theory based on molecular orbital coefficients and/or coupled cluster

From the 2nd to 8th, I arrange them according to their priorities, as well as their difficulties and required time.

I think the reason is how we understand what is an issue and what belongs to the roadmap. Therefore, please feel free to move the above terms into issues if you think it should. Thank you.

**Comment by bast** [comment]
I will lift the above list into issues - it does not belong here since it has very little to do with the issue title.

**Comment by ringholm** [comment]
Update: Daniel's documentation considered as part of work for https://github.com/openrsp/openrsp/issues/61 .

**Comment by ringholm** [comment]
for after release v1.0.0

**Comment by ringholm** [comment]
This topic is adequately brought to attention in #61 and considered to be part of it, so I'm closing the present issue not due to resolution but due to it already being raised in #61.
