### ISSUE TITLE
Tentative rules and/or coding standards for developers

### ISSUE THREAD

**Issue by bingao** [openrsp/openrsp#39]
Hi @bast and @ringholm 

I previously wrote a tentative rules (`doc/developer/rules.rst`) on how to design and prepare codes/tests/documentation for OpenRSP, which in my opinion, is not very strict on the coding style/requirements.

Radovan also had coding standards for developers, `doc/developer/coding_standards.rst`, which does have some rules/suggestions on coding (though I do not follow all of them :-), for instance, I like to write `end subroutine` and `end function` with name, in particular for long subroutines/functions).

Therefore, could you please decide:

1. Should we have both rules and coding standards or not?
2. If yes, is it better that we merge them into one single file?
3. Of course, please modify/improve these rules/standards.

**Comment by ringholm** [comment]
I think this document was written mainly with us core developers in mind. If we want this to be a general set of guidelines for "outside developers", we may want to expand it and make sure that the present code adheres to the guidelines. Also, maybe there is an official spot for this kind of document on the repository page here on GitHub?

**Comment by bast** [comment]
The standard would be to put it in `CONTRIBUTING.md`: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

Totally fine to relax some of them.
