### ISSUE TITLE
Restructure website/documentation before release

### ISSUE THREAD

**Issue by bingao** [openrsp/openrsp#42]
Hi @bast and @ringholm 

I think after Magnus finishes his work on website/documentation, and we finish issues related to website/documentation, we can perform a last round polish before release. Here are some questions:

1. I would prefer that more people, or better all principal authors can take a look at the website and documentation, and make their comments/changes. How do you think?
2. If you all agree, should we assign people from the issue or by mailing list?
3. Should we set a deadline for such group polish work?
4. What is the appropriate/efficient way to do this group work? Making a branch that everyone can push, and then finally pull request to the master?

Thank you.

**Comment by bast** [comment]
1. Everybody.
2. I prefer if people self-assign to signal that they actually work on it and actually have time to work on it.
3. OK for me.
4. One branch per issue. Everybody sends pull-requests towards master.

**Comment by ringholm** [comment]
1. I agree that we should get all the principal authors to at least approve the website/documentation and it is also great if as many of them as possible are actively involved with the text.
2. I agree with Radovan.
3. I want to get a better idea about what the whole website/documentation contains and lookslike now and I will get started on this after completing some other "active" points on my list.
4. Again agree with Radovan.

All in all, my currnt impression is that we cannot complete all of the remaining work by November 1st but there is also not a very large amount of work left. I intend to raise this point on the mailing list today and it may be easier to plan the remaining work after this.

**Comment by ringholm** [comment]
I have now found myself doing work on several of the issues in one branch despite what I wrote for point 4 above - sorry about that.

**Comment by bast** [comment]
OK - I will wait until you are through, and then I can do a round.

**Comment by ringholm** [comment]
Renamed issue to "Restructure website/documentation before release". I have now pushed a branch `website-overhaul`. I have made a first commit there which restructures the index page in the new form, plus some other changes. I also have made a document to keep track of files whose reference was removed from the index page so they are not forgotten. This list should be updated as reference to those files are reinstated or possibly recombined into other files. After this initial commit I will branch off from `website-overhaul` for the upcoming work.

**Comment by ringholm** [comment]
Update: Part of this is now done by #48. Will move on to the next part.

**Comment by ringholm** [comment]
Issue for the next part opened as #49.

**Comment by ringholm** [comment]
Issue #49 now closed. Looking over it one more time before the final merge.

**Comment by bast** [comment]
Super! Then I will do a round.

**Comment by bast** [comment]
Can this issue be closed? Can we spawn off smaller, bite-size issues?

**Comment by ringholm** [comment]
That's fine with me

**Comment by bast** [comment]
Is there anything in this issue which is not solved or not followed-up in a smaller issue?

**Comment by ringholm** [comment]
I think that the main remaining point in this issue is the task of having the interested authors do an iteration on the website. If that is not by itself sufficient to justify keeping this issue (I for one am done with my iteration) then the issue should be closed.

**Comment by bast** [comment]
OK closing. I think the documentation has matured that we can now work in parallel on it and we can signal to others what we are trying to solve by creating issues and self-assigning issues.

**Comment by ringholm** [comment]
I agree
