### ISSUE TITLE
Do an iteration on the new introduction section

### ISSUE THREAD

**Issue by ringholm** [openrsp/openrsp#47]
In the reorganized website, the introduction section is called "About the project" and consists of the following files:

```
   what_is_openrsp.rst
   authors.rst
   citations.rst
   history.rst
   programs_with_openrsp.rst
   papers_openrsp_calcs.rst
```

This issue is for my work on these documents - i.e. the "what is OpenRSP and why?", authors list, citation guide, history of OpenRSP, list of programs with OpenRSP, and papers where OpenRSP was used for calculations.

**Comment by ringholm** [comment]
@bast by the way, I seem to recall that it is possible to "hot-build" the website locally to view my changes. Is that true?

**Comment by bast** [comment]
Absolutely!
```
$ sphinx-build doc/ _build
```

**Comment by ringholm** [comment]
Great, thanks!

**Comment by ringholm** [comment]
Fixed by PR https://github.com/openrsp/openrsp/pull/48.
