### ISSUE TITLE
Do an iteration on the "how to..." parts of the website

### ISSUE THREAD

**Issue by ringholm** [openrsp/openrsp#49]
I will make a first new version of the "Do you want...?" sections of the website as described in https://github.com/openrsp/openrsp/issues/29#issuecomment-435027127 . For this purpose, I will branch off from `website-overhaul` into `website-overhaul-howto`.

I plan to make a quite slim version of this part of the site for now and we can later put in relevant and potentially updated parts of older existing documents.

**Comment by bast** [comment]
But `website-overhaul` is now merged so better branch off `master`. Let's try to reduce the number of branches and let's please keep them short-lived. Also if this is a "one person" branch, better do it on a fork to again minimize the number of branches here.

**Comment by ringholm** [comment]
The last PR was from `website-overhaul-introduction` into `website-overhaul`. I only anticipate one more branching off like this (`website-overhaul-howto`) and then all of `website-overhaul` can be merged back into `master`.

**Comment by bast** [comment]
OK - over time I would like the number of branches here reduce to very few: master and release branches.

**Comment by ringholm** [comment]
That's certainly a goal but in this case I was quite pleased with myself for my structuring :)

**Comment by bast** [comment]
Sorry, yes, I got confused about the PR - I somehow thought it went towards master.

**Comment by ringholm** [comment]
Fixed by #51, closing.
