### ISSUE TITLE
Polish information and documentation files before release

### ISSUE THREAD

**Issue by bingao** [openrsp/openrsp#5]
To be done before release:

1. Look through RST files in the root directory and "doc" directory
2. Update "ChangeLog" if we still keep it
3. Update "openrsp.bib" if we still keep it

**Comment by bast** [comment]
Please split these into individual issues. Then it is much easier to take them and resolve them. I am now working on hooking up the RST sources with http://www.openrsp.org and also #2.

**Comment by bast** [comment]
1 is too vague IMO, 2 and 3 are followed up in #8 and #9, respectively.
