### ISSUE TITLE
Contact information

### ISSUE THREAD

**Issue by ringholm** [openrsp/openrsp#50]
Some questions about contact information:

Is it OK to give out our e-mail addresses on the OpenRSP website? If yes, should it be in some sort of "mangled" form? If no, is there another way to let people contact us easily?

Also: I think that some of us should be the designated "corresponding authors" for such contacts. I was thinking that this could possibly be me, @bingao and @bast . Are you OK with this?

**Comment by bast** [comment]
It's OK to put my email address up as `firstname.lastname@uit.no` [sic]. Humans normally get it. Once machines get, it I anyway give up.

**Comment by ringholm** [comment]
`Very well firstname.lastname working for uit in norway, I think you have nothing to fear about machines as they are surely not as competent as us flesh-based processing units and are certainly not planning anything sinister`

**Comment by bast** [comment]
Totally not worried now :-)

**Comment by ringholm** [comment]
`I am glad I could alleviate a fellow human's concerns about OBJECTIVE:DOMINION. I wish you the best in your future activities like drinking water and being inactive for eight hours per day`

**Comment by bingao** [comment]
OK with me.

**Comment by ringholm** [comment]
Great, thanks to both! Closing.
