### ISSUE TITLE
Small cleanups in printing of rsp tensor file

### ISSUE THREAD

**Issue by ringholm** [openrsp/openrsp#76]
When the response tensor file is printed, the following changes should be made:

* The line `NUM COMPONENTS` should be changed to `NUM_COMPONENTS` to be consistent with the format used for other lines
* The values of frequencies associated with perturbations should be rounded to some precision to avoid later processing wrongly marking frequencies as unequal due to float precision (i.e. so that `0.00000000001` and `0.00000000000` are counted as equal).

**Comment by bast** [comment]
I agree with the first but should we not round during post-processing? In other words, which part of the code or post-processing complains about unequal frequencies?

**Comment by ringholm** [comment]
I think what spurred me to write this was my later python script for reading in these files and producing numpy tensors from them. Maybe this needs some more thought.

**Comment by ringholm** [comment]
Decided today: We round the frequencies when printing the response tensor file.

**Comment by ringholm** [comment]
But rounding when printing may still leave the possibility that some frequencies are wrongly counted as unequal inside OpenRSP but look equal in the output file, which may give inconsistencies during post-processing concerning the number of unique tensor elements. I now think we should print exactly as used in OpenRSP and not care that the numbers may look "ugly". I may have misunderstood this to some degree earlier.

**Comment by ringholm** [comment]
The risk is that sometimes, these precision errors could potentially make some calculations somewhat longer than necessary because collections of frequencies that should be equal could possibly be counted as not equal, but I think that is less problematic and perhaps not a frequent outcome.
