### ISSUE TITLE
Bugfix fourth order derivative and XCInt

### ISSUE THREAD

**Issue by kdu002** [openrsp/openrsp#80]
Following error message

lsdalton.x: /cluster/home/kdu002/Programs/LSDalton-xc-untested/build/xcint/src/xcint-build/balboa/src/balboa/balboa/Main.cpp:82: int Main::get_geo_offset(int, int, int) const: Assertion `id < geo_offset_size' failed.

when running acetonitrile 4GEO, pcseg-2, PBE0.

**Comment by bast** [comment]
Thanks for posting this. The error comes from a dependency of XCint which is a dependency of LSDalton. I might move that issue to a different repo since the bugfix will likely not affect this repo but still good to have it here visible.

**Comment by kdu002** [comment]
Inputs:

```
**WAVE FUNCTIONS
.DFT
PBE0
*DENSOPT
**GENERAL
.NOGCBASIS
**INTEGRAL
.NO SCREEN
.NOFAMILY
**OPENRSP
*SOLVER
*RESPONSE FUNCTION
$PROPERTY
.PERTURBATION
4
GEO
GEO
GEO
GEO
.KN-RULE
1
*END OF INPUT
```

and 

```
ATOMBASIS
This file have been generated using the WRITE_MOLECULE_OUTPUT subroutine
Output is in Bohr
Atomtypes=3    Charge=0   Nosymmetry
Charge= 1.00  Atoms=3     Basis=pcseg-2
H        -13.15909467      4.10521645      1.75436281
H        -12.46881125      1.45243448     -0.17177481
H        -13.23399416      4.39313244     -1.58257918
Charge= 6.00  Atoms=2     Basis=pcseg-2
C        -12.26848589      3.49529833      0.00002031
C         -9.61809317      4.18525907      0.00000422
Charge= 7.00  Atoms=1     Basis=pcseg-2
N         -7.51763178      4.73241531     -0.00001447
```

**Comment by bast** [comment]
This is now solved:
- https://github.com/bast/balboa/commit/f7c0e4377e50847fadb88c24bc08d53e887f499b
- https://gitlab.com/dalton/lsdalton/commit/36d1c29184284019b96d73ba2eb7c5bb9cb6d542
