### ISSUE TITLE
Make the v1.0.0 release

### ISSUE THREAD

**Issue by ringholm** [openrsp/openrsp#93]
@bast @bingao @KennethRuud @danielhfriese @simensr 

I'm collecting here various final tasks before the release for a better overview:

* Part of this process overlaps with settling #69 and #43  
* Mint the release (@bast)
* Update LSDalton manual with DOI to release, refer to that commit from LSDalton (@bast)
* Settle (@ringholm and @KennethRuud) final questions about the format of the data from residue calculations, may possibly warrant small changes
* Make release notes (@ringholm to start)

These are all the things I know about that remain - please add others if you know about them.

**Comment by ringholm** [comment]
I have here a suggestion for the -

OpenRSP v1.0.0 release notes:

Code:

* Now requires Fortran 2008
* Rewrote linked list functionality for caching to instead use (reallocating) arrays
* "Number of components" marker in rsp_tensor output file now written as 'NUM_COMPONENTS' instead of 'NUM COMPONENTS'
* Significantly decreased usage of array constructors in function/subroutine arguments
* Now compiles and runs with most compilers but still problems with some Intel/2019 setups
* Fixed various memory leak/out-of-bounds errors that sometimes would happen
* OpenRSP now looks for available file units before choosing one to use
* Disabled internal memory limit and memory bookkeeping, may be reinstated later
* If a response tensor is large, then if it's printed at the debugging print level, it's broken down into smaller chunks
* Added stops for various currently unsupported residue calculation setups
* Fixed a bug concerning testing of perturbation frequencies against excitation energy for residue calculations
* Removed some unused residue-related routines
* Calculation setup errors encountered in wrapper routines now cause exit, not just warning and then continuing

Project:

* Added contribution guide and authorship process guide
* Updated pull request template to solicit agreement to contribution terms
* Various changes to documentation

**Comment by ringholm** [comment]
This was formed from making an "executive summary" of the commits since v1.0.0-alpha.

**Comment by bast** [comment]
For next time we can work with a milestone or issue labels to avoid that we have several issues that deal with the same thing. Release list looks good, this is what I will add to the "release", like here: https://github.com/bast/runtest/releases

**Comment by ringholm** [comment]
Good idea @bast about the milestone, and that sort of place was exactly what I pictured the list would go into.

**Comment by bast** [comment]
But then again this is a really useful meta-issue to keep us on track. Thanks for pulling everything together.

**Comment by ringholm** [comment]
Update: I spoke with Daniel right now and he and Kenneth have now settled the residue data format questions to my satisfaction. @bast I would like to add the following point to the release notes:

* The "excitation" perturbation in a single residue calculation is now given the label EX1 in the rsp_tensor file; however, its current implementation still results in triplication of the calculation result data due to being treated as having three components when in fact it has got only one

With this change, there are no further known unsettled issues that would affect the release. However, I am doing some stress tests with LSDalton right now and if they finish over the weekend, I would like to see if they reveal anything further which would affect the release. Apart from this we should be all set for the release of v1.0.0 here.

**Comment by bast** [comment]
Great! Let me know when it's the right time and I will then create the release and DOI.

**Comment by ringholm** [comment]
So @bast the stress tests have so far not revealed anything conclusive and they are likely to time out before running into any further problems that would warrant delaying the release.

However, as I mention in https://gitlab.com/dalton/lsdalton/-/issues/85 , we see many failing OpenRSP tests for Intel 18 builds on the current https://testboard.org/cdash/index.php?project=LSDalton . I'm not sure if we went over this already and it's an explanation we know about, but if not, we may want to change the release note point

* Now compiles and runs with most compilers but still problems with some Intel/2019 setups

to instead be

* Now compiles and runs with most compilers but still problems with some Intel/2018 and Intel/2019 setups

**Comment by bast** [comment]
I will send a PR soon to add release notes to the repository so that we have them in one place and then I can simply copy-paste them to the release preparation form.

**Comment by ringholm** [comment]
Nice! I think we will go ahead and warn about Intel/2018 too, just to be on the safe side.

**Comment by bast** [comment]
Followed-up in #101. Closing the issue to have fewer discussion streams.
